### ISSUE TITLE
No playback, mpsyt returns to the list of found records.

### ISSUE THREAD

**Issue by ZaxonXP** [mps-youtube/yewtube#799] opened 2018-03-01 11:14 UTC
Mpsyt goes back to the list of found videos without playing anything.

## Issue
When I try to play any of the video/audio then mpsyt tries to get the file, but the moment it should run the player it goes back to the result list. I tried mpv/mplayer/vlc players and none of them works.

Please advise how to debug the issue.

## My Environment
OS: Debian 8.10 Jessie
mpsyt: v0.2.8
mpv: 0.8.3
vlc: 2.2.8

**Comment by vn-ki** [comment] 2018-03-01 11:20
Mpsyt is probably running into an error while fetching the steam and trying to play the item. The log would be the obvious way of debugging. 

Does this happen with every video? Try scrolling up to see if there are any error messages you missed.

**Comment by ZaxonXP** [comment] 2018-03-01 11:56
How can I get the log file?

I scrolled up, but there was no any error.

**Comment by Paz666** [comment] 2018-03-02 05:23
Same problem here, It doesn't happen with every video, but it does with a lot of them.

**Comment by vn-ki** [comment] 2018-03-02 12:51
Open mpsyt with `mpsyt --debug`. Log can be found in the file `/tmp/mpsyt.log`.

**Comment by ZaxonXP** [comment] 2018-03-05 11:45
Here is what the log produced:

**Comment by vn-ki** [comment] 2018-03-05 12:06
This is most probably related to #753. This is already fixed in the `develop` branch. Try that version to see if your problem is fixed.

@ids1024 You should probably push that commit to the master branch and release a new version as this bug is affecting many users.

**Comment by ZaxonXP** [comment] 2018-03-05 15:32
OK, tried to install the dev version with the following command:

`pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git`

The installation was without an error, but execution complains about player import: 
[mps_err.log](https://github.com/mps-youtube/mps-youtube/files/1781464/mps_err.log)

**Comment by vn-ki** [comment] 2018-03-05 17:21
That is bug! It's due to a cyclic import in `misc.py` caused by `lastfm.py`. I will fix it and open a PR soon.

**Comment by dgalaktionov** [comment] 2018-03-07 15:56
I've been using some old version just fine, but today I've installed 2.8 from pip in another computer and this happened to me. Trying to install it from the repository like @ZaxonXP did gave me the same error on execution.

So I've worked around this issue and others [in my own fork](https://github.com/dgalaktionov/mps-youtube/commit/8cbb3fd7e30c9ad964ea847219abf4522e83a0d6). I am not going to make a PR because instead of sorting out the `lastfm` dependency problem I've just removed it along with its scrobble feature (whatever it means).

`pip3 install --user -U git+https://github.com/dgalaktionov/mps-youtube.git`

While I'm grateful to whoever is running the project, this lack of stability is harming the users who don't have the time or skill to make it work.

**Comment by ipatch** [comment] 2018-03-08 23:20
> I've installed 2.8 from pip in another computer

@dgalaktionov you we're _in another computer_? How did you get inside a computer in the first place?

![https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif](https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif)

**Comment by tngotran** [comment] 2018-04-19 04:13
The development branch upto Mar 8 solved this bug. Thanks

**Comment by qwerm** [comment] 2018-05-26 18:26
Same thing here after I updated to 0.2.8 on Linux (Debian Stretch). I tried 
`pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git`
But the problem persisted even then

**Comment by synnema** [comment] 2018-09-29 09:48
Hi, I was in the same trouble, and tryed :
pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git

on Raspberry Pi 3:
__________________________________________________________
pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git
Collecting git+https://github.com/mps-youtube/mps-youtube.git
  Cloning https://github.com/mps-youtube/mps-youtube.git to /tmp/pip-bi5a0vpc-build
Collecting pafy!=0.4.0,!=0.4.1,!=0.4.2,>=0.3.82 (from mps-youtube==0.2.8)
  Downloading https://files.pythonhosted.org/packages/b0/e8/3516f761558525b00d3eaf73744eed5c267db20650b7b660674547e3e506/pafy-0.5.4-py2.py3-none-any.whl
Installing collected packages: pafy, mps-youtube
  Running setup.py install for mps-youtube ... done
Successfully installed mps-youtube-0.2.8 pafy-0.5.4
[11:44:07] pi@raspberrypi:~$ pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git            mpsyt --debug
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.09.18
Python version     : 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124]
Processor          : 
Machine type       : armv7l
Architecture       : 32bit, ELF
Platform           : Linux-4.14.69-v7+-armv7l-with-debian-9.4
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/pi/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : cs_CZ.UTF-8
env:LANGUAGE       : cs_CZ.UTF-8
______________________________________________________

And now I can play all videos with no problem. Thank you for solution.

ZV

**Comment by damvee** [comment] 2020-02-08 17:43
just play dont install. go to directory mps-youtube, and then execute with ./mpsyt and enjoy :)

**Comment by rbreaves** [comment] 2021-02-18 23:48
> Hi, I was in the same trouble, and tryed :
> pip3 install --user -U git+https://github.com/mps-youtube/mps-youtube.git

That comment was gold by @synnema!

**Closed** 2023-03-21 05:43 UTC
