### ISSUE TITLE
Playback stops after 2 minutes

### ISSUE THREAD

**Issue by edheldil** [mps-youtube/yewtube#543] opened 2016-10-17 09:20 UTC
For several days (maybe weeks) now, playback of any song I try hangs exactly after 2 minutes. mpsyt process waits in sock_alloc_send_pskb.

I use 'develop' branch of mpsyt.

**Comment by ids1024** [comment] 2016-10-20 20:19
Duplicate of #242

Can you tell if that `sock_alloc_send_pskb` call is in python or in mpv/mplayer?

If you are using mplayer, try mpv (and vice versa).

**Comment by freeasinbear** [comment] 2016-10-21 09:29
Just came to see if there were any progresses on this issue and found this new post.. I can't use mpv because it doesn't seem to find "full albums", but just songs (and fewer results than mpsyt). It happens only when on audio-only mode.
I don't get any errors, sadly (I'm using mpsyt installed with pip3).
Anyway if it might be useful, to me it doesn't happen if the pause is very short (like a couple of seconds), only when it is a bit more longer.

Couldn't it be that mpsyt thinks that you paused for too long and stops getting data from youtube (that in the meantime buffered for about 2 minutes)? If not a mpsyt issue, couldn't it be from the youtube's side?

**Comment by sollericos** [comment] 2017-02-20 09:55
Hi,
This is happening to me too.
mps-youtube-0.2.7.1
Pafy-0.5.3.1
youtube-dl-2017.02.16
No error seen in command line, syslog, messages... 
Is this still happening to any one else?

**Comment by rccrdpccl** [comment] 2019-02-06 08:36
I had the same problem, but switching from mplayer to mpv seems to have solved the issue

**Comment by kudo-shinichi** [comment] 2019-05-06 07:53
i had the same problem, switching from mplayer to mpv solves the problem for me.

**Closed** 2023-01-28 03:16 UTC
