### ISSUE TITLE
Mpv crashes mps-youtube, and MPlayer plays only 1mn. 

### ISSUE THREAD

**Issue by galgot** [mps-youtube/yewtube#1128] opened 2020-12-01 15:29 UTC
Hi, as the title says, setting mpv as player and trying to read a track makes mpsyt quit with this error : 
```
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 8, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/player.py", line 79, in play
    self._playsong()
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/player.py", line 138, in _playsong
    self._launch_player()
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/player.py", line 298, in _launch_player
    self.launch_player(cmd)
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 135, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/usr/local/lib/python3.8/site-packages/mps_youtube/players/mpv.py", line 188, in _player_status
    if resp['data'] is not None:
KeyError: 'data'
```

If setting player to MPlayer, it reads only 1 minute of the track.
I also get this msg before it reads : 
```
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
```

This is on a MacBook Pro running Mac OS X 10.11.6. Here infos on the mpsyt install : 
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.11.26
Python version     : 3.8.5 (default, Sep  9 2020, 23:31:58)
[Clang 8.0.0 (clang-800.0.42.1)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : macOS-10.11.6-x86_64-i386-64bit
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /Users/galgot/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : fr_FR.UTF-8

MPV is version 0.33.0
and 
MPlayer is 1.3.0-4.2.1
these are  Macports installed.

**Comment by galgot** [comment] 2020-12-01 17:31
Ok, let me make precisions about reading with MPlayer after some test. It doesn't read exactly 1 mn. It's more that it just doesn't finish the track, stops before the end. Sometime it reads the whole track, but it's completely random...

**Comment by justmeandopensource** [comment] 2020-12-13 08:46
I have the same problem. After the 2 or 3 attempts, the video plays.

**Comment by darkhz** [comment] 2020-12-13 13:51
@galgot Hi there, I believed I solved the issue with mpv-related audio playback.

The (very small) fix has to be done across two files:
/home/rohit/.local/lib/python3.9/site-packages/mps_youtube/player.py
/home/rohit/.local/lib/python3.9/site-packages/mps_youtube/mpris.py

In **player.py**, comment out lines **530-532**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change' and resp['id'] == 1:
	if resp['data'] is not None:
		elapsed_s = int(resp['data'])
...

```
In **mpris.py**, comment out lines **224-225**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change':
	self.setproperty(resp['name'], resp['data'])
...
```

I believe this problem happened as a result of bugfixes to mpv (0.7.x).
Do tell if this solves your problem or not.

**Comment by darkhz** [comment] 2020-12-13 13:56
@galgot Hi there, I believed I solved the issue with mpv-related audio playback.

The (very small) fix has to be done across two files:
$PATH_TO_PYTHON_LIB/python3.9/site-packages/mps_youtube/player.py
$PATH_TO_PYTHON_LIB/python3.9/site-packages/mps_youtube/mpris.py

In **player.py**, comment out lines **530-532**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change' and resp['id'] == 1:
	if resp['data'] is not None:
		elapsed_s = int(resp['data'])
...

```
In **mpris.py**, comment out lines **224-225**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change':
	self.setproperty(resp['name'], resp['data'])
...
```

I believe this problem happened as a result of bugfixes to mpv (0.7.x).
Do tell if this solves your problem or not.

**Comment by darkhz** [comment] 2020-12-13 17:39
@galgot  Hi there, I believed I solved the issue with mpv-related audio playback.

The (very small) fix has to be done across two files:
$PATH_TO_PYTHON_LIB/python3.9/site-packages/mps_youtube/player.py
$PATH_TO_PYTHON_LIB/python3.9/site-packages/mps_youtube/mpris.py

In **player.py**, comment out lines **530-532**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change' and resp['id'] == 1:
	if resp['data'] is not None:
		elapsed_s = int(resp['data'])
...

```
In **mpris.py**, comment out lines **224-225**, which shows the following snippet:
```
...
if resp.get('event') == 'property-change':
	self.setproperty(resp['name'], resp['data'])
...

```
I believe this problem happened as a result of bugfixes to mpv (0.7.x).
Do tell if this solves your problem or not.

There's another related issue with mpv, where the following error message comes
every time you try playing a track:

> Error parsing commandline option title: option requires parameter
> Make sure you're using e.g. '--title=value' instead of '--title value'

Aren't you facing this?

Side note, I installed mps-youtube via pip.

(Sorry for the reposting, I encountered another error and wan't sure whether this patch was correct)

**Comment by Masacaai** [comment] 2021-01-20 10:51
This is a duplicate of [this issue](https://github.com/mps-youtube/mps-youtube/issues/1134).
Apply the changes mentioned in that commit and it should start working as intended.

**Closed** 2023-01-28 03:24 UTC
