### ISSUE TITLE
random crash i keep getting

### ISSUE THREAD

**Issue by autoteelar** [mps-youtube/yewtube#1138] opened 2021-01-05 12:51 UTC
on the latest pip3 install the development version
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/mpris.py", line 227, in bindmpv
    self.setproperty(resp['name'], resp['data'])
KeyError: 'data'
Traceback (most recent call last):
  File "/bin/mpsyt", line 33, in <module>
    sys.exit(load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')())
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/main.py", line 153, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/main.py", line 70, in matchfunction
    func(*matches)
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/commands/play.py", line 102, in play
    g.PLAYER_OBJ.play(songlist, shuffle, repeat, override)
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 79, in play
    self._playsong()
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 138, in _playsong
    self._launch_player()
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/player.py", line 298, in _launch_player
    self.launch_player(cmd)
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/players/mpv.py", line 135, in launch_player
    self._player_status(self.songdata + "; ", self.song.length)
  File "/home/ralts/.local/lib/python3.9/site-packages/mps_youtube/players/mpv.py", line 188, in _player_status
    if resp['data'] is not None:
KeyError: 'data'

**Comment by autoteelar** [comment] 2021-01-05 12:53
i think its caused by pressing Q in mpv

**Comment by autoteelar** [comment] 2021-01-05 13:00
it also happens randomly for some videos before it starts playing, like when i press 6 to play the 6th one in the list

**Comment by Masacaai** [comment] 2021-01-20 10:48
This is a duplicate of [this issue](https://github.com/mps-youtube/mps-youtube/issues/1134).
Apply the changes mentioned in that commit and it should start working as intended.

**Comment by autoteelar** [comment] 2021-01-31 10:04
thank you :D

**Comment by autoteelar** [comment] 2021-01-31 10:05
i will try

**Closed** 2023-01-28 03:03 UTC
