### ISSUE TITLE
playback error

### ISSUE THREAD

**Issue by JPRuehmann** [mps-youtube/yewtube#669] opened 2017-08-13 11:04 UTC
If I try to play a Title I get the following error and the Volume controls wont work.
`Exception in thread Thread-2: 00:00:02 [1%]   [=>                                                                                                                               ] vol: 95%
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'`
Thanks

**Comment by JPRuehmann** [comment] 2017-08-16 11:37
python -m install does the Trick, but the Volume Controls still won´t work.
If I enter 1...0 nothing happens. everything else works fine.

**Comment by ritiek** [comment] 2017-08-16 11:46
The volume is controlled using <kbd>0</kbd> and <kbd>9</kbd>. Can you confirm?

**Comment by JPRuehmann** [comment] 2017-08-16 18:53
If I press Enter on the Kyboard or the Keypad with Numpad active or not nothing happens.

**Comment by James-Firth** [comment] 2017-12-11 20:08
I get the same error during search and playback

**Comment by iamtalhaasghar** [comment] 2023-03-21 14:50
duplicate of https://github.com/mps-youtube/yewtube/issues/861

**Closed by iamtalhaasghar** 2023-03-21 14:50 UTC
