### ISSUE TITLE
mps-youtube crashes when searching for something. 

### ISSUE THREAD

**Issue by ghost** [mps-youtube/yewtube#725] opened 2017-11-25 00:39 UTC
[mps-youtube crashes](https://user-images.githubusercontent.com/33970402/33225879-ce002a2a-d145-11e7-9f18-4e5929886ad6.png) when searching for something. The only setting I've changed so far is "set show_video true", to which even when I disabled that it still does the same thing.

```> Exception in thread Thread-1:
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 3497, in preload
    stream = get_streams(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```

Is this a bug, or a fault on my behalf somehow?

* OS: Ubuntu 16.04.3 
* Host: Surface Pro 3 
* Kernel: 4.4.6-3-surface

**Comment by ritiek** [comment] 2017-11-25 04:53
Do you have `youtube-dl` up to date? Most errors are caused by `youtube-dl` being outdated.

**Comment by vozycozyx** [comment] 2017-11-25 07:28
@ritiek This is most likely the issue. I will see in the morning. Thanks for the advice.

**Comment by ZirconCode** [comment] 2017-12-15 21:45
So `apt install mps-youtube` seems broken for me on Ubuntu, even installing the required pip3 youtubed-dl afterwards did nothing. Removing and installing mpsyt via pip3 worked.

**Comment by iamtalhaasghar** [comment] 2023-03-21 14:50
duplicate of https://github.com/mps-youtube/yewtube/issues/861

**Closed by iamtalhaasghar** 2023-03-21 14:50 UTC
