### ISSUE TITLE
crash with the search word "garbage"

### ISSUE THREAD

**Issue by nost4252** [mps-youtube/yewtube#674] opened 2017-08-16 18:09 UTC
just wanted to listen to Garbage the band :)
keep up the good work!

=====================================

Searching for 'garbage'                                                                                                                              
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 141, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.6/site-packages/mps_youtube/main.py", line 64, in matchfunction
    func(*matches)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 212, in search
    _search(term, query, msg, failmsg)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 41, in _search
    loadmsg=loadmsg)
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/songlist.py", line 56, in paginatesongs
    songs = func[s:e]
  File "/usr/lib/python3.6/site-packages/mps_youtube/util.py", line 47, in __getitem__
    self.ilist.append(next(self.iterable))
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 28, in iter_songs
    for song in get_tracks_from_json(wdata2):
  File "/usr/lib/python3.6/site-packages/mps_youtube/commands/search.py", line 342, in get_tracks_from_json
    'id': ','.join([get_track_id_from_json(i) for i in items])}
TypeError: sequence item 9: expected str instance, dict found

======================================

mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.08.13
Python version     : 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.12.6-1-ARCH-x86_64-with-arch-Arch-Linux
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/user/.config/mps-youtube
env:TERM           : rxvt-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

**Comment by ritiek** [comment] 2017-08-16 18:19
Duplicate of #663. This should be fixed on the `develop` branch (#664). Can you confirm?

@ids1024 I think putting a short note in README or just publishing a new release on pypi should help prevent such duplicates and a drain on both sides.

**Closed** 2023-03-21 14:52 UTC
