### ISSUE TITLE
suggestion: non-blocking play and search 

### ISSUE THREAD

**Issue by elig0n** [mps-youtube/yewtube#1007] opened 2019-08-30 01:25 UTC
right now if one plays song/playlist one can't search.
a use case would be for adding songs to playlist while already listening to music from it.
the screen could be splitted in two letting the user to focus on either and use them without blocking.

**Comment by iamtalhaasghar** [comment] 2023-07-06 18:05
Duplicate of #983

**Closed** 2023-07-06 18:06 UTC
