### ISSUE TITLE
Audacious stops too early

### ISSUE THREAD

**Issue by itsfarseen** [mps-youtube/yewtube#1130] opened 2020-12-08 18:45 UTC
If I use audacious as the player with mpsyt, it stops playback in the middle.

Config:
![image](https://user-images.githubusercontent.com/40014472/101527164-aa0f7100-39b3-11eb-9dff-b8bf6f39dc55.png)

**Comment by SeanPaulCampbell** [comment] 2021-05-21 20:39
I have a similar problem with mplayer.

**Comment by iamtalhaasghar** [comment] 2023-01-28 04:04
Duplicate of #242

**Closed** 2023-01-28 04:04 UTC
