### ISSUE TITLE
Automatically save the downloaded track

### ISSUE THREAD

**Issue by ununhexium** [mps-youtube/yewtube#883] opened 2018-09-04 06:37 UTC
## Autosave played tracks

I wasn't able to find that feature. There is download, or play, but not save while playing.

Would be nice to autosave the tracks that are played to use them faster / offline later on.
This would be a config option somewhere, disabled by default.

**Comment by iamtalhaasghar** [comment] 2023-07-06 18:36
Duplicate of #658

**Closed** 2023-07-06 18:36 UTC
