### ISSUE TITLE
Error in the command for installation on macOs

### ISSUE THREAD

**Issue by OsKaR31415** [mps-youtube/yewtube#1186] opened 2022-01-11 14:11 UTC
The given command for installation on macOs is `brew cask install mpv`.
Sadly this syntax got deprecated, and isn't valid anymore.
The new syntax is `brew install --cask mpv` (that worked for me)

**Comment by iamtalhaasghar** [comment] 2023-01-28 02:54
Duplicate of #1163

**Closed** 2023-01-28 02:54 UTC
