### ISSUE TITLE
Problem when donwload video.

### ISSUE THREAD

**Issue by Luis15Herr** [mps-youtube/yewtube#893] opened 2018-10-04 20:44 UTC
> dlurl https://www.youtube.com/watch?v=GX8Hg6kWQYI
Traceback (most recent call last):
  File "/usr/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4231, in dl_url
    yt_url(url)
  File "/usr/lib/python3/dist-packages/mps_youtube/main.py", line 4243, in yt_url
    p = pafy.new(url)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 148, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 866, in __init__
    self.fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 892, in fetch_basic
    smaps, js_url, mainfunc, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 481, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by iamtalhaasghar** [comment] 2023-03-21 14:50
duplicate of https://github.com/mps-youtube/yewtube/issues/861

**Closed by iamtalhaasghar** 2023-03-21 14:50 UTC
